### ISSUE TITLE
Overview appears in front of applications if Escape is pressed after a text search.

### ISSUE THREAD

**Issue by spxak1** [pop-os/cosmic-workspaces#11]
If you open applications (super+a) start typing to search and hit Esc, the overview appears over the applications.

See video here (half way through look for when I type): https://streamable.com/cc0bpn

When vertical overview is disabled, when performing the same sequence (Super+a, then type, then Esc) will just show the workspace thumbnail.

See video here (after halfway. look for when I type): https://streamable.com/3jc4zl

Thank you.

**Comment by leviport** [comment]
Just to confirm, you're running 21.10?

**Comment by spxak1** [comment]
> Just to confirm, you're running 21.10?

Yes, Clean install of the beta.

**Comment by WatchMkr** [comment]
The current Applications view is being replaced in 21.10 so closing this issue.
