### ISSUE TITLE
21.10: Incorrect scaling when connected to 4k monitor

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/cosmic-workspaces#16]
The workspaces view has issues scaling across monitors with different resolutions. The issue is exacerbated when scaling on the smaller monitor is greater than the bigger monitor.

Look at the workspaces view on the smaller monitor, each workspace is unusually small, and the gap at the bottom is unusually big.
![bad_scaling](https://user-images.githubusercontent.com/58987761/139288961-12747296-323e-4383-81b6-3a6a7b2be25e.png)

The greater the difference in scaling, the worse the issue gets. This is 100% on a 4k monitor, and 200% on the 1080p monitor
![ugly_scaling](https://user-images.githubusercontent.com/58987761/139291135-0f984ce2-a987-4a97-bd37-5cdea5df18d1.png)

**Notes**
Tested on 21.10

**Comment by jackpot51** [comment]
Is this with wayland or with hidpi-daemon?

**Comment by leviport** [comment]
This was discussed in back channels some time ago, but to summarize:

- The HiDPI daemon doesn't seem to be the culprit
- It happens on X, but I'm not sure about Wayland
- I've seen it on an Nvidia-only laptop with a 4k internal display and a 1080p external display, as well as an Intel-only laptop with a 1080p internal display and a 4k external display. 

The key for me was to set all displays to 100% scaling and the 4k display as the primary display. Then the workspace picker on the 1080p display will be scaled down.

I'm not sure if it provides any clues, but when testing https://github.com/pop-os/cosmic-workspaces/pull/23, I noticed a different picker scaling bug while using a 4k display at 100%.

**Comment by 13r0ck** [comment]
I believe this is fixed by #25
