### ISSUE TITLE
Upload to Gnome Extensions

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/cosmic-workspaces#21]
The [READEME.md](./README.md) currently links to the vertical-overview page in gnome extensions.
>You install it through [Gnome Extensions](https://extensions.gnome.org/extension/4144/vertical-overview/).

This should link to a gnome extensions page for cosmic-workspaces to make it easier for users to install, but cosmic-workspaces has not been uploaded yet.

**Comment by jackpot51** [comment]
We intentionally do not want to upload this fork of vertical-overview to make sure it is installed with the correct version for the same version of Pop!_OS.
