### ISSUE TITLE
Windows overlap to the Workspaces view on big screens

### ISSUE THREAD

**Issue by ghostcat1001001** [pop-os/cosmic-workspaces#24]
Since the last optical update, windows are overlaped to the the overview of Workspaces on big screens (even with lower resolution).
Happens on Pop!_OS 21.10 on Oryp Pro (oryp6) with on Hybrid Mode as well as on NVIDIA Mode on my 28 inch external display.

When does it happens?
- only on big screens
- & only if dock and workspace are on the same site

Important?
- no, it's just a quality-of-life bug.

**Comment by ghostcat1001001** [comment]
![screenshot](https://user-images.githubusercontent.com/66872288/144624018-35cbdff0-7cff-463e-b82a-da3319684492.png)

**Comment by leviport** [comment]
Thank you for the report. We are tracking this issue here: https://github.com/pop-os/cosmic-workspaces/issues/4
