### ISSUE TITLE
21.10: search bar in workspaces view

### ISSUE THREAD

**Issue by enm4x** [pop-os/cosmic-workspaces#27]
Hello,

First, thanks for all the works you've done on this cool distro :smile: 

I've installed the latest 21.10 and found out there is no more the research bar when in workspaces mode. 

Is this a bug or the new implementation ? 

thanks

**Comment by rimijoker** [comment]
@enm4x in cosmic there is no research bar in the workspaces mode, but if you open the application menu, you would find the research bar there. However, if you like things the GNOME way, you can always disable cosmic specific extensions.

**Comment by 13r0ck** [comment]
This is intentional. Please use the cosmic launcher! (Activated by pressing `Super` by default)
