### ISSUE TITLE
21.10: Window previews sometimes don't dodge the workspace picker in applications view

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-workspaces#4]
This doesn't seem to be happening on my main work machine, but I have seen it on a couple testing machines. The screenshots pretty much say it all:

![Screenshot from 2021-10-06 15-15-56](https://user-images.githubusercontent.com/13512097/136293857-dc39c142-bb2f-4af2-8dd4-57d30f1d84bc.png)
![Screenshot from 2021-10-06 15-18-04](https://user-images.githubusercontent.com/13512097/136293860-d87021d1-e948-4daf-b87d-96631e2db86c.png)
![Screenshot from 2021-10-06 15-18-12](https://user-images.githubusercontent.com/13512097/136293862-470f8a85-0c53-4a76-a4e6-f0b10274f520.png)

I first started noticing it while testing https://github.com/pop-os/gnome-shell-extension-vertical-overview/pull/3, but it seems to happen regardless of whether I have that branch added or not.

**Comment by isantop** [comment]
This seems to happen most commonly when the workspaces are located on the left.

**Comment by jmbuhr** [comment]
Somewhat related: My workspace picker is really tiny on the main monitor (right):
![image](https://user-images.githubusercontent.com/17450586/137295056-6bcd5456-ac04-4566-897f-7f734485fbbb.png)
The tiny orange thing in the top right corner is actually it

**Comment by jmbuhr** [comment]
The vertical overview extension from https://extensions.gnome.org/extension/4144/vertical-overview/ as opposed to this fork seems to work fine for me.

**Comment by chrsrns** [comment]
I hope this can help.

On my install, the overlapping goes away when turning off the `Vertical overview` extension, then turning it on again. It doesn't persist on reboot, though.

Also, the above "fix" works on [this issue](https://github.com/pop-os/beta/issues/224).

**Comment by jacobgkau** [comment]
Still seeing this on test machines; when it happens, I can't drag windows to other workspaces via the mouse on the affected display (but I can drag them to workspaces on other displays, and drag windows between displays on the active workspace.)

**Comment by jackpot51** [comment]
This is somewhat fixed by https://github.com/pop-os/cosmic-dock/commit/888ddc5f5e5a495e3cd2b232bf2a3f42c1f5f084

**Comment by jackpot51** [comment]
The only edge case left is dock on the same side as workspace picker

**Comment by leviport** [comment]
Definitely much better after https://github.com/pop-os/cosmic-dock/commit/888ddc5f5e5a495e3cd2b232bf2a3f42c1f5f084

As mentioned, there is still a little overlap if the dock and the workspace picker are both on the same side.

Besides that, only one other tiny nitpick. When the picker is on the right side, the big orange close button that gets overlayed in the Workspaces view overlaps it just a little.

![Screenshot from 2021-11-09 14-05-28](https://user-images.githubusercontent.com/13512097/141004670-dc612576-bf38-4c45-9357-74445100c9fa.png)
