### ISSUE TITLE
System freezes when opening Application Launcher

### ISSUE THREAD

**Issue by duck-dev** [pop-os/cosmic-workspaces#42]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Application Launcher/Library

**Issue/Bug Description:**

I just updated from Pop! OS 21.04 to 21.10. The update seemed to be successful. After the reboot, I had to re-enable the Dash-To-Panel plugin again, so I can get my customized taskbar back, which seemed to disappear after the update (which shouldn't be the case in my opinion, unless there is a specific reason to it).
After I've done that, I tried to open the Application Launcher/Library, which caused the entire system to freeze. I could only move my mouse, otherwise nothing worked, no keyboard shortcuts, nothing. I tried to reboot and do the same thing again - same issue. Nothing responds.

**Steps to reproduce (if you know):**

- Upgrade to 21.10
- Try to open Application Launcher from the taskbar after the reboot

**Expected behavior:**

The system should obviously not freeze if I want to use the Application Launcher. :)

**Other Notes:**

I'm really sorry if I opened this issue in the wrong repository. I'm not sure where such a report would fit the best. 
From all the "freeze reports" all over the internet and Pop! OS repositories, they all seemed to happen randomly at some time. In my case however, it happens with no other applications running, almost the entire memory is available and in a specific situation (when trying to open the Application Launcher), not "randomly" as other people often describe.

This only happened after the 21.10 update and I didn't touch the hardware before/in-between. That's why I highly doubt it's specifically a hardware issue, that's triggered by the attempt to open the Application Launcher (through the taskbar).

**System Specifications:**
CPU: Intel® Core™ i7-3770 CPU @ 3.40GHz × 8 
RAM: 15.6 GB (16 GB, 4 x 4 GB RAM)
GPU: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB]
HDD: Works fine, 2 TB
SSD: Works fine, 2 x 128 GB

**Comment by 13r0ck** [comment]
Probably related to #35

**Comment by 13r0ck** [comment]
Does #41 fix your issue?

**Comment by 13r0ck** [comment]
https://github.com/pop-os/cosmic-workspaces/issues/35#issuecomment-1095584310

**Comment by Hamdan85** [comment]
this is still happening!
