### ISSUE TITLE
Dash to Panel conflicts - thumbnails issue

### ISSUE THREAD

**Issue by jsaxx** [pop-os/cosmic-workspaces#48]
When using the extension alongside dash to panel, the workspace thumbnails are bugged.

Toggling the extension on-off did intermittently fix the issue, but only up until reboot.

![2022-02-07_22-47](https://user-images.githubusercontent.com/71516796/152877519-ac713826-a744-490c-9cde-07c4a5e80057.png)

**Comment by 13r0ck** [comment]
Duplicate of #43
