### ISSUE TITLE
21.10: picker previews scale strangely when many workspaces are created

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-workspaces#5]
This is a lot more apparent with the new picker styling:
![Screenshot from 2021-10-07 10-03-43](https://user-images.githubusercontent.com/13512097/136428424-1f94e674-7951-4f7d-aeff-f43e8447665e.png)

but it does still happen without the styling applied:
![Screenshot from 2021-10-07 10-38-46](https://user-images.githubusercontent.com/13512097/136428313-b23a4b35-90d8-4016-8edf-1b3cbb02bfb4.png)

The top preview also starts to touch the top edge of the picker box as more workspaces get created, and that happens before the picker box is filled up.

**Comment by jackpot51** [comment]
Assigning to @13r0ck since he already wrote the PR fixing it. Thanks Brock!
