### ISSUE TITLE
[Pop!_OS] Shortcuts for "Move to workspace left"/"Move to workspace right" are not configurable via GUI after disabling COSMIC Workspaces

### ISSUE THREAD

**Issue by rafaeltgt** [pop-os/cosmic-workspaces#50]
**(1) Issue/Bug Description:**
I'm using Pop Os with Cosmic Dock, Cosmic Workspaces and Pop COSMIC extensios disabled. I noticed that the shortcuts for switching workspaces stop working after disabling Cosmic Workspaces extension. 

After disabling cosmic workspaces extension, the shortcuts for "Move to workspace above / below" won´t work anymore, even if I add a custom shortcut, it does not work. 

**(2) Steps to reproduce (if you know):**
Disable Cosmic Workspace extension. 
Try to move to workspace below with Ctrl + Super  + Down
Add new shortcut for "move to workspace below"
Try new shortcut

**(3) Expected behavior:**
Move to workspace below should work with Ctrl + Super  + Down or newly added shortcut

**(4) Distribution (run cat /etc/os-release):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"

**(5) Gnome Shell version:**
GNOME 40.5 

**6) Pop Shell version (run apt policy pop-shell or provide the latest commit if building locally):**
pop-shell:
Installed: 1.1.0~1643736613~21.10~afb4f12

**Comment by jacobgkau** [comment]
Stock GNOME 40/41 does not have vertical workspaces. Without COSMIC Workspaces enabled, your workspaces should be horizontal, so the shortcuts for "Move to workspace left/right" would be needed instead. Are you using a different extension to achieve vertical workspaces without COSMIC Workspaces?

**Comment by rafaeltgt** [comment]
> Stock GNOME 40/41 does not have vertical workspaces. Without COSMIC Workspaces enabled, your workspaces should be horizontal, so the shortcuts for "Move to workspace left/right" would be needed instead. Are you using a different extension to achieve vertical workspaces without COSMIC Workspaces?

I'm not using additional extension. 
There is no "Move to workspace left/right" shortcut in settings

**Comment by jacobgkau** [comment]
>  There is no "Move to workspace left/right" shortcut in settings

It was patched out for Pop!_OS: https://github.com/pop-os/mutter/commit/01e827fe92163949a2324ecad0ec4c578c4cb2b0 

You can set it via the terminal with these commands:

```
gsettings set org.gnome.desktop.wm.keybindings witch-to-workspace-left "['<Primary><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings witch-to-workspace-right "['<Primary><Super>Right']"
```

The "issue" here is that the GUI doesn't change which shortcuts are configurable in GNOME Control Center based on whether the extension is enabled or disabled.

**Comment by rafaeltgt** [comment]
@jacobgkau Thank you. It worked.
