### ISSUE TITLE
22.04: workspace OSD is horizontal / default Gnome

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-workspaces#55]
The styling of the workspace indicator OSD when changing workspaces is default Gnome and horizontal:

![Screenshot from 2022-03-29 11-04-15](https://user-images.githubusercontent.com/13512097/160672370-01caf271-7fe2-4ede-beb1-a0905e3b5083.png)
![Screenshot from 2022-03-29 11-04-16](https://user-images.githubusercontent.com/13512097/160672382-eb774169-3634-46d6-874c-ec8e011cf98c.png)

It also collides with the dock with default dock settings.

**Comment by jackpot51** [comment]
It looks like #56 will try to fix this
