### ISSUE TITLE
Pop!_OS 22.04 Beta - Workspaces are broken

### ISSUE THREAD

**Issue by Chinchzilla** [pop-os/cosmic-workspaces#59]
Hello System76, 

after update 5th of April 2022, the application launcher and menu were fixed, but workspaces are completely broken. When you click workspaces, you just see a wallpaper and can interact only with system tray, dock disappears,only fix is to restart the shell or log out and login.

Thank you for your work and effort, we appreciate you!

Regards,
Chinchzilla

**Comment by leviport** [comment]
Might be fixed by https://github.com/pop-os/cosmic-workspaces/pull/56

**Comment by 13r0ck** [comment]
#56 has been merged. Please upgrade your system tomorrow and workspaces should be working again.
