### ISSUE TITLE
Cosmic - Workspaces | alignment issue | Right Side of screen | > 4 workspaces 

### ISSUE THREAD

**Issue by sysdrum** [pop-os/cosmic-workspaces#68]
At this time the right side of screen alignment gap issue has not gone away when using greater than 4 workspaces.
![issuewithcosmicworkspaces](https://user-images.githubusercontent.com/6105336/165292668-b818609a-8689-4b97-994f-e05445a4a84a.jpg)

**Comment by leviport** [comment]
Thanks for the report!

@13r0ck is this one you want to take a look at?

**Comment by sysdrum** [comment]
Is there tile factor limit at a set resolution? 
1080p
1440
4k

**Comment by 13r0ck** [comment]
@sysdrum I don't understand your question?

**Comment by sysdrum** [comment]
Well the issue is not happening on my 4k display with 8 workspaces, but at 1440 > 6 it has the issue and 1080p > 4
You made the change moved from an if statement to a constant.
``` const gap = 16 * scaleFactor; ```
I was wondering if it was related to JSON Tile placement ( I am not sure what gnome calls it related to scaling and resolution)
