### ISSUE TITLE
Animation awkwardness when "Hide scaling workspaces" enabled

### ISSUE THREAD

**Issue by spxak1** [pop-os/cosmic-workspaces#7]
Hi again,

another minor thing to consider. When "Hide scaling workspaces" is disabled, the background image scales to the centre of the screen in an animation that reveals the dash and the workspaces picker, as if they were always hiding behind the background. This is nice.

However, if "Hide Scaling Workspaces" is enabled, and the background is not scaled to the centre, the dash and workspaces picker appear suddenly, while the app windows move to the centre, and even more suddenly (and with some delay, maybe only on my hardware) they disappear once the overview is released.

There is no animation for the dash and picker, which is fine when "Hiding scaling workspaces" is disabled, but makes the whole thing awkward when enabled.  This becomes more prominent when "Static Background" is enabled to keep the background on overview.

Please consider as you wish.

Thank you.

**Comment by spxak1** [comment]
Here's a video to demonstrate how the picker and dock **suddenly** appear. 

https://streamable.com/tsi5ro

Same video shows a number of issues (Cosmic dock pushing the background image up when transitioning from overview, I'll report this in the Cosmic dock github page) and the fact that a full Alt+F2+r is required if the dock is re-enabled to centre the overview again (see end of video).

In 3.38, the picker emerged from the side, with a smooth animation that matched the motion of the windows.

Thank you.

**Comment by WatchMkr** [comment]
@leviport we will need to remove options in the Cosmic Dock and Cosmic Workspaces extensions and suggest users visit Settings for workspace options. As such, I'm not sure that this one should stay open.

**Comment by leviport** [comment]
I figured leaving it open would be a reminder to remove the option, but I'm ok with closing this if a reminder is not needed.

**Comment by jacobgkau** [comment]
> I figured leaving it open would be a reminder to remove the option

We at least have https://github.com/pop-os/beta/issues/264 still open that mentions this as well, although it's primarily covering a different issue.
