### ISSUE TITLE
Mouse moves when switching workspace with multiple monitors

### ISSUE THREAD

**Issue by spacekookie** [pop-os/cosmic-workspaces#76]
I have GNOME configured to only have one workspace for the external monitor. Whenever I plug my laptop into an external monitor and switch to another workspace (with the gestures), the mouse sometimes jumps to various locations.

From what I have experienced (with a maximised firefox window on the external monitor workspace):

- When switching from an internal workspace with a window to an empty workspace, the mouse jumps to the top left corner of the window on the external workspace
- When switching from an empty workspace to a workspace with a window, the mouse will _sometimes_ jump to the top left conern of the window on the internal workspace
- When switching between two workspaces both with windows on them, the mouse will not jump

Running Pop_OS:

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
```
Latest state of updates on the 23.06.2022:

```
 ❤ (theia) ~> sudo apt list --upgradable                                                                  
Listing... Done
```

**Comment by n3m0-22** [comment]
I was able to exactly replicate this issue following the steps listed above.

**Comment by leviport** [comment]
Does this behavior still happen if you turn off this setting in Extensions > Pop-shell settings?

![2022-06-24_08-46](https://user-images.githubusercontent.com/13512097/175560058-7b4ec7b5-a924-4132-bab8-c86e717440fc.png)

**Comment by n3m0-22** [comment]
Yes that fixes it on mine.

**Comment by leviport** [comment]
That _should_ change the mouse cursor behavior, so I'm going to close this for now. Let us know if the problem persists with that setting deactivated, and we can reopen this issue.

**Comment by mrj0** [comment]
Ahh thank you, this was driving me nuts. I didn't turn this setting on and I found it unexpectedly moving my cursor after upgrading to 22.04.

**Comment by spacekookie** [comment]
Hey! Sorry for the long delay, I was on vacation :camping: 

Disabling that setting fixes this for me too. I'm wondering what that setting is supposed to do though, because it doesn't seem like anyone would want this enabled as a default :thinking: Or is the feature just buggy on multi-monitor setups?

**Comment by leviport** [comment]
> I'm wondering what that setting is supposed to do though, because it doesn't seem like anyone would want this enabled as a default 

It's a preference thing, but I enjoy the feature, including on my triple-display setups. It moves the mouse cursor to whichever window has focus. That means if I have a window focused on my left display, then shift focus to a window on my right display, I don't have to scoot my mouse all the way across two monitors to click on the newly-focused window.
