### ISSUE TITLE
Workspace picker over dash when Cosmic dock disabled

### ISSUE THREAD

**Issue by spxak1** [pop-os/cosmic-workspaces#8]
The screenshot shows the problem.

![Screenshot from 2021-10-13 10-56-59](https://user-images.githubusercontent.com/29977030/137111744-7ad2db59-b7c7-4c47-bc34-3d18aa49e730.png)

There is no way to move the default dash to the other side. Also the option to move the workspace picker is found in the Gnome-Settings→Desktop→Workspaces. Rather far from where everything other setting of the vertical picker is.

Please consider.

Thank you.

**Comment by 13r0ck** [comment]
I don't have a specific PR that fixed this. But the dock can now be moved.
