### ISSUE TITLE
focus in workspaces overview disappears partially or completely using arrow keys to navigate 

### ISSUE THREAD

**Issue by Mop5264** [pop-os/cosmic-workspaces#81]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
when you have more than one workspace, all of them with open apps, when you press super + d you will see miniatures with opened apps
![image](https://user-images.githubusercontent.com/111230786/184939871-d6fc49b6-c97e-450f-8164-dcb5b314348e.png)
the yellow dot with white "X" represents focus. Then when you press arrow down two times the focus dot disappear as in the image below
![foto3](https://user-images.githubusercontent.com/111230786/184940270-23cd2e50-047a-4842-ab95-eceee79b4837.png)

**Steps to reproduce (if you know):**
- fill at least two workspaces with applications
- then if you play with changing focused window with arrows then you will find out that focus dot could be lost

**Expected behavior:**
- focus dot should not be lost

**Other Notes:**
when you have only one workspace, everything work perfectly

**Comment by n3m0-22** [comment]
I can replicate this issue, but the focus dot cycles back to the top window preview with one more press of the down arrow. Does that not happen for you?

**Comment by Mop5264** [comment]
in simple example like here if I press down arrow one more time then yes, focus dot cycles, but in reality when i have 4 or 5 workspaces with plenty of applications focus dot often disappear and does not cycles at all, you can bring it back by mouse clicking or according to this example, pressing few times up arrow.

**Comment by n3m0-22** [comment]
I tested this with between 3 and 8 workspaces and at least 5 apps open on each. I never could get it to disappear completely. I did notice a pattern. If I'm in X after the indicator disappears pressing the down arrow 3 more times cycles it back. In Wayland it only take 2 more presses of the down arrow to cycle back. Changing from dynamic to fixed workspaces seems to have no effect.

**Comment by Mop5264** [comment]
i have checked it again, when pressing down arrow, you were right, but when pressed up arrow the focus dot disappear and never shows again.

**Comment by n3m0-22** [comment]
After pressing the up arrow I see it disappear, but it comes back if I press the down arrow again. Is that not happening for you?

**Comment by Mop5264** [comment]
it works exactly as you describe ;P i meant if you will be pressing only up arrow it will not cycles at all

**Comment by MohitOhlyan** [comment]
Hey! I was having some trouble with workspace and found this issue. It seems like the `X` Button shows when you hover over the window. Can you try with just hovering your mouse over the windows instead of clicking them?

**Comment by n3m0-22** [comment]
@Mop5264 Are you still having this issue?

**Comment by MohitOhlyan** [comment]
> @Mop5264 Are you still having this issue?

I think it was caused by the Extension and I disabled the extension and after that no.

**Comment by n3m0-22** [comment]
@MohitOhlyan as far as I can tell this issue was resolved. When using the arrow keys to navigate overview the up arrow does not cycle backwards on workspaces after the first one, but it does show back up with one click of the down arrow. Is that the issue you were having?

**Comment by MohitOhlyan** [comment]
> @MohitOhlyan as far as I can tell this issue was resolved. When using the arrow keys to navigate overview the up arrow does not cycle backwards on workspaces after the first one, but it does show back up with one click of the down arrow. Is that the issue you were having?

Yes I think it is resolved. But now we have a different issue I last checked which is caused by a extension. For now I believe this issue is fixed. I haven't had any problem with Workspaces in last month. Works flawlessly. Awesome work 👍

**Comment by MohitOhlyan** [comment]
I will like to add is that the focus do get back as soon as you hover it with mouse. I believe it is a feature not a bug. If your mouse pointer is not on any window in workspaces, there is no focus then.

**Comment by Mop5264** [comment]
Hi, now i see improvement in how workspaces behave, but still when i open few of them after pressing arrow down few times focus dot disappear (this issue does not occur when i have one workspace)
![img1](https://user-images.githubusercontent.com/111230786/203846417-674c424e-a9c5-41aa-950e-5004d9f742af.png)
![img2](https://user-images.githubusercontent.com/111230786/203846433-f78aa127-446d-4ef1-a4e9-ad29635fad43.png)
after pressing down arrow one or two times more the focus dot back but in my opinion correct behavior is when focus dot never disappear @n3m0-22 

i've tested it on ma local machine and on virtual machine both of them upgraded to current newest available version
