### ISSUE TITLE
Workspace picker padding and distances from other objects

### ISSUE THREAD

**Issue by spxak1** [pop-os/cosmic-workspaces#9]
All screenshots with the default 300/300/0 (Left Offset/Right Offset/Thumbnail position)

![Screenshot from 2021-10-13 11-04-44](https://user-images.githubusercontent.com/29977030/137112848-693aa992-387f-4593-9afa-f3eb6c6b2af9.png)

The default 1+1 screen: Too much space at the top, distance to panel not equal to distance to bottom, distance from left end not related to distance of dash to end of screen on the other side.

![Screenshot from 2021-10-13 11-04-17](https://user-images.githubusercontent.com/29977030/137113215-7d12d813-01c9-4b72-ae9f-6b4032d1e70e.png)

Adding more workspaces tries to fit them all, but while scaled, the all line up on the right. More prominent in next screenshot.

![Screenshot from 2021-10-13 11-03-58](https://user-images.githubusercontent.com/29977030/137113337-a080e633-ead2-4b83-aceb-10bd65094104.png)

As a result the picker is not aligned, leaving empty space on the left.

Workspace Thumbnail Position makes no difference.

Please consider,

Thank you.

**Comment by leviport** [comment]
Final point is being tracked here: https://github.com/pop-os/gnome-shell-extension-vertical-overview/issues/5

**Comment by isantop** [comment]
It looks like there may have been an upgrade bug, as many of the settings appear to be broken (the background isn't correct, COSMIC Dock is not in use, etc.)

**Comment by spxak1** [comment]
> It looks like there may have been an upgrade bug, as many of the settings appear to be broken (the background isn't correct, COSMIC Dock is not in use, etc.)

I will clean install and test again.

In above screenshots, COSMIC is disabled (I was testing the standard dash at the same time) and "blur my shell" is enabled (not sure if it makes a difference.

Thanks.

**Comment by isantop** [comment]
Ah yeah. There may indeed be issues when using the extension without COSMIC or COSMIC Dock, as the components are currently all designed to work together.

**Comment by spxak1** [comment]
> Ah yeah. There may indeed be issues when using the extension without COSMIC or COSMIC Dock, as the components are currently all designed to work together.

Is this going to be the case in the release version? A disclaimer about it may save time and effort in support questions. But ideally it'd be nice if we could mix and match (I don't use Cosmic, as I don't want a dock on my screen but still prefer the vertical workspaces). Thanks again.

**Comment by isantop** [comment]
I don't see the dependency on various components changing, but you can leave COSMIC enabled and disable the dock on the screen.

**Comment by spxak1** [comment]
> I don't see the dependency on various components changing, but you can leave COSMIC enabled and disable the dock on the screen.

Thanks again. I will experiment with this option. A disclaimer may save a lot of users from confusion (especially people with other docks and those who have no idea what they're doing -see reddit questions after the upgrade).

Thanks for your time.

**Comment by 13r0ck** [comment]
Closed via #23
